// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq-QsHcTqw3siPtgRMWcp_2I0ln5VCFTg',
    appId: '1:174133724339:web:7d3682a040466d611bdcc6',
    messagingSenderId: '174133724339',
    projectId: 'schood-5d09c',
    authDomain: 'schood-5d09c.firebaseapp.com',
    storageBucket: 'schood-5d09c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMTMRr7JG88N8updjLJh93ZT1BOdzqT7s',
    appId: '1:174133724339:android:a1147252f94f61b51bdcc6',
    messagingSenderId: '174133724339',
    projectId: 'schood-5d09c',
    storageBucket: 'schood-5d09c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADvhd2adVBVmi3ydy_B_usu2Rb6dKeKAk',
    appId: '1:174133724339:ios:b245d1f9558750021bdcc6',
    messagingSenderId: '174133724339',
    projectId: 'schood-5d09c',
    storageBucket: 'schood-5d09c.appspot.com',
    iosClientId: '174133724339-dvk57g64vghv0c2rkeod52olojdq3r0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.schood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADvhd2adVBVmi3ydy_B_usu2Rb6dKeKAk',
    appId: '1:174133724339:ios:9b4542782a9eae171bdcc6',
    messagingSenderId: '174133724339',
    projectId: 'schood-5d09c',
    storageBucket: 'schood-5d09c.appspot.com',
    iosClientId: '174133724339-jf1kkr75t2qck00ge511a3l71elp285p.apps.googleusercontent.com',
    iosBundleId: 'com.example.schood.RunnerTests',
  );
}
