// ignore: constant_identifier_names
const String text_drogues_services =
    "Vous pouvez joindre Drogues info service au 0 800 23 13 13, de 8h à 2h, 7 jours sur 7. Votre appel est anonyme et gratuit. Que vous soyez directement ou indirectement concerné directement ou indirectement par l'usage de drogues, n'hésitez pas à appeler Drogues info service, vous y trouverez des professionnels formés aux problèmes de la consommation de drogues et de la dépendance. Une écoute confidentielle et sans jugement Des informations précises, une aide personnalisée";
// ignore: constant_identifier_names
const String text_ecoute_cannabis =
    "Ecoute Cannabis est un numéro pour tous les consommateurs de cannabis et leur entourage. Il propose des informations sur les effets, les risques, la loi, les lieux d’accueil concernant le cannabis. Il permet de discuter avec des écoutants spécialisés qui apportent du soutien, des conseils de prévention, et orientent vers des professionnels compétents. Horaires: 7j/7 de 8 h à 2 h Tél: 0 980 980 940";
// ignore: constant_identifier_names
const String text_ecoute_alcool =
    "Alcool info service est un service qui dépend depuis le 1er mai 2016 de l’agence Santé publique France, établissement public administratif sous tutelle du ministère chargé de la Santé. Alcool info service est le service national d’aide à distance en matière d’alcool et de dépendances. Il a également en charge le recensement, la mise à jour et la mise à disposition du public de l’annuaire national des structures spécialisées en addictologie Vous pouvez joindre Alcool info service au 0 980 980 930, de 8h à 2h, 7 jours sur 7. Votre appel est anonyme et non surtaxé (coût d’une communication locale depuis un poste fixe, ou inclus dans les forfaits des box et des mobiles). Tel 0 9800 980 930";
// ignore: constant_identifier_names
const String text_tabac_ecoute =
    "Le 39 89, c’est quoi ? C’est la ligne téléphonique de Tabac info service. Elle vous met en relation avec des professionnels de l’arrêt du tabac. Vous profitez d’un accompagnement entièrement gratuit, avec un suivi personnalisé. Vous pouvez appeler quand vous voulez du lundi au samedi, de 8h à 20h. Un conseiller répondra à vos premières questions. Si vous le souhaitez, il vous mettra en relation avec un tabacologue. Ensemble, vous pourrez faire le point sur votre tabagisme et trouver la stratégie d’arrêt qui vous convient le mieux. Ce sera toujours le même tabacologue qui vous accompagnera : vous fixerez avec lui des rendez-vous téléphoniques réguliers. C’est lui qui vous rappellera au moment que vous aurez choisi.";
// ignore: constant_identifier_names
const String text_sida_service =
    "Depuis 30 ans, SIS Association (Sida Info Service) œuvre dans le domaine de la lutte contre le VIH, les IST, les hépatites et pour la prévention et la santé sexuelle. SIS Association combat aussi l'homophobie, la sérophobie et la transphobie, grâce à un dispositif complet de relation d’aide à distance en santé (RAD) conjuguant des sites internet, une écoute et une réponse par téléphone, livechat, mail, sur notre forum et via les réseaux sociaux (Facebook, Twitter, Instagram, Youtube) permettant ainsi une couverture large des problématiques de santé. 7 jours sur 7 (jours fériés compris), de 8 h à 23 h, en France métropolitaine et les départements d'outre-Mer, Sida Info Service 0 800 840 800 est à l'écoute de tous* : que vous soyez séronégatif-ve, séropositif-ve, malade ou proche d'une personne touchée, que vous n'ayez pas fait le test de dépistage ou que vous soyez en attente de résultats. Chaque appel est accueilli avec respect, sans jugement. Enfin, la confidentialité permet à chacun-e de s'exprimer librement. L'appel est gratuit (depuis un téléphone fixe et portable) et non décompté des forfaits depuis la France.";
// ignore: constant_identifier_names
const String text_enfant_maltraite =
    "Les problématiques de dangers gérées quotidiennement par les écoutants du 119 sont multiples : une majorité des appels concerne des violences subies par les enfants (violences psychologiques, physiques et sexuelles), notamment au sein de la famille ou en institution. Le 119 est également contacté pour d’autres problématiques de dangers...Qui peut appeler le 119 ? Les enfants confrontés à une situation de risque et de danger, pour eux-mêmes ou pour un autre enfant qu'ils connaissent. Les adultes confrontés ou préoccupés par une situation d’enfant en danger ou en risque de l’être : famille proche, famille élargie, voisins, communauté éducative...";
// ignore: constant_identifier_names
const String text_violences_conj =
    "SOS Femmes Vendée propose une écoute téléphonique 24h/24 et 7j/7. Le contact téléphonique reste à ce jour le principal moyen pour nous joindre. Toute victime peut nous contacter par téléphone pour s’informer, s’entretenir sur son vécu et sa problématique, être guidée et soutenue à tout moment de son parcours, et à toute heure du jour et de la nuit. L’ensemble des salariées assure ce service. Le 17 : numéro qui vous permet de joindre la police et la gendarmerie. Le 112 : numéro d’appel unique européen pour accéder aux services d’urgence, valable dans l’Union Européenne.Le 15 : numéro spécifique aux urgences médicales, qui vous permet de joindre 24h/24 le service d’aide médicale urgente (SAMU).Le 18 : numéro qui vous permet de joindre les pompiers. Le 114 : numéro d’urgence pour les personnes sourdes ou malentendantes victimes ou témoins d’une situation d’urgence, afin de solliciter l’intervention des services de secours (en remplacement des 15, 17, 18)Le 115 : numéro qui vous permet de solliciter un hébergement d'urgence.";
// ignore: constant_identifier_names
const String text_SOS_amitie =
    "S.O.S Amitié est un service d’aide par l’écoute. Au 09 72 39 40 50, ainsi qu’en chat et messagerie, ses écoutants bénévoles accueillent la parole de toute personne qui traverse une période difficile et qui ressent le besoin d’être entendue et écoutée dans sa souffrance. L’écoute S.O.S Amitié est gratuite, inconditionnelle et sans jugement ni conseil. Elle offre à chaque appelant(e) la possibilité de mettre des mots sur sa souffrance. Elle vise à desserrer l’angoisse, aide à prendre du recul, à reprendre confiance en ses propres ressources et à retrouver, pour certains, le simple goût de vivre.";
// ignore: constant_identifier_names
const String text_sans_abris = "";
// ignore: constant_identifier_names
const String text_croix_rouge = "";
// ignore: constant_identifier_names
const String text_sante_jeunes = "";
// ignore: constant_identifier_names
const String text_viols_femmes =
    "Apporte aux personnes qui ont subi des violences sexuelles une écoute, un soutien, une solidarité ainsi que des informations nécessaires aux différentes démarches qu’elles peuvent entreprendre, tout en respectant leur anonymat. 0 800 05 95 95 du lundi au vendredi, de 10h à 19h Anonyme et gratuit, y compris depuis les portables";
